// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dPrUNtMVOElmQIKgux2W2S3arQgduAs',
    appId: '1:166387390805:web:0b1edfd1b2d3b2072a77dc',
    messagingSenderId: '166387390805',
    projectId: 'seamstress-e737e',
    authDomain: 'seamstress-e737e.firebaseapp.com',
    storageBucket: 'seamstress-e737e.firebasestorage.app',
    measurementId: 'G-VYEG24ZB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZh6fmZDvG1VT4bu7-b1Pao7-USDZWKPg',
    appId: '1:166387390805:android:3a68f706fcc7c76a2a77dc',
    messagingSenderId: '166387390805',
    projectId: 'seamstress-e737e',
    storageBucket: 'seamstress-e737e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdjNexkzrrxPWm83pAAm7vLvSGUQJzBA',
    appId: '1:166387390805:ios:4081d2c007df73132a77dc',
    messagingSenderId: '166387390805',
    projectId: 'seamstress-e737e',
    storageBucket: 'seamstress-e737e.firebasestorage.app',
    iosBundleId: 'com.example.seamstress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-dPrUNtMVOElmQIKgux2W2S3arQgduAs',
    appId: '1:166387390805:web:d84350f5644d7e4e2a77dc',
    messagingSenderId: '166387390805',
    projectId: 'seamstress-e737e',
    authDomain: 'seamstress-e737e.firebaseapp.com',
    storageBucket: 'seamstress-e737e.firebasestorage.app',
    measurementId: 'G-ZEV8LXK61C',
  );

}